apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx-helm
spec:
  admin_user: admin
  service_type: ClusterIP
  postgres_data_volume_init: true
  ingress_type: ingress
  ingress_host:
    - hostname: awx.scadrial.lan
    - hostname: awx.scadrial.lan
      tls_secret: tls-secret
  ingress_annotations: |
    environment: testing
  ingress_controller: ingress-nginx
