apiVersion: v1
kind: Service
metadata:
  name: mistral-7b
  namespace: default
spec:
  ports:
  - name: http-mistral-7b
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: mistral-7b
  sessionAffinity: None
  type: ClusterIP
