createResource: true
resource:
  name: mongodb-replica-set
  version: 8.0.4
  members: 3
  tls:
    enabled: false
    useX509: false
    sampleX509User: false
    useCertManager: true
    certificateKeySecretRef: tls-certificate
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h   # 365 days
      renewCertBefore: 720h   # 30 days
