controller:
  admin:
    username: "admin"
    password: "admin"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    hostName: jenkins.scadrial.lan
    tls:
     - secretName: jenkins.scadrial.lan
       hosts:
         - jenkins.scadrial.lan
  prometheus:
    enabled: true
    serviceMonitorAdditionalLabels:
      resource: prometheus-stack