controller:
  metrics:
    enabled: true
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack
  installPlugins:
    - prometheus:795.v995762102f28